title: AdamAppLock
description: Privacy & Terms
theme: minima
# So internal links like /privacy/ work from a project site
baseurl: "/AppLock"
url: "https://boda7s.github.io"

# Optional nav (minima supports header_pages)
header_pages:
  - index.md
  - privacy-policy.md
  - terms-of-use.md
